FROM node:latest

RUN apt update && \  
    apt install -y xdg-utils \ 
        libnss3 \                        
        libnspr4 \            
        libatk1.0-0 \         
        libatk-bridge2.0-0 \  
        libcups2 \            
        libatspi2.0-0 \       
        libxdamage1 \         
        libxkbcommon0 \       
        libasound2

CMD [ "/bin/sh" ]