version: '3'

services:
  node:
    image: node:latest
    working_dir: /app
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: everyworkout
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
