import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../../utils/api";

import { Heading, Navigation, RecordCard, Loading, Paginator } from "../../components";

const Profile: NextPage = () => {

  const { data, isLoading, isSuccess } = api.profile.get.useQuery();

  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <Navigation />
      <div className="grid md:grid-cols-12 bg-gray-50">
        <div className="md:col-span-6 md:col-start-4">
          <section className="mb-2 p-2">
            {isSuccess && <>
                <p className="text-sm text-gray-500">ログインユーザー(公開されません)</p>
                {data?.image && <img src={data.image}></img>}
                <div className="text-lg font-bold">{data?.name}</div>
                <div>{data?.email}</div>
            </>}
          </section>
        </div>
      </div>
    </>
  );
};

export default Profile;
