import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import { Navigation } from "../../components/Navigation";
import { Badge } from "../../components/Badge";
import { api } from "../../utils/api";

const Dashboard: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div>{id}</div>
    </>
  );
};

export default Dashboard;
