import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Navigation } from "../../components/Navigation";
import { Badge } from "../../components/Badge";
import { api } from "../../utils/api";

const Dashboard: NextPage = () => {
  const { data } = api.muscle.getAll.useQuery();
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div>
        {data?.map((d) => (
          <Badge key={d.id} label={d.name}></Badge>
        ))}
      </div>
    </>
  );
};

export default Dashboard;
