import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useSession } from "next-auth/react";
import { api } from "../../utils/api";

import { Navigation, RecordCard, Loading } from "../../components";

const History: NextPage = () => {
  const { data: sessionData } = useSession();
  const [skip, setSkip] = useState<number>(0);
  const [perPage, setPerPage] = useState<number>(10);
  const [date, setDate] = useState<string>(
    new Date().toISOString().split("T")[0] || ""
  );
  const { data, isLoading, isSuccess } =
    api.workout.getUserWorkouts.useQuery({
      date: new Date(date).toISOString(),
      skip,
      take: perPage,
    });
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className="grid md:grid-cols-12 bg-gray-50">
        <div className="md:col-span-6 md:col-start-4">
          <section className="mb-2 p-2">
            <p className="text-sm text-gray-500">トレーニング履歴</p>
            <div className="mb-2">
              <label
                className="mb-2 block text-sm font-bold text-gray-700"
                htmlFor="date"
              >
                日付を選択
              </label>
              <input
                className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                id="date"
                type="date"
                placeholder="日付"
                value={date}
                onChange={(e) => setDate(e.target.value)}
              />
            </div>
            {isLoading && <Loading />}
            {isSuccess && (
              <>
                {data?.length && data?.length > 0
                  ? data?.map((d) => {
                    return <RecordCard key={d.id}
                      id={d.id}
                      exerciseName={d.exercise.name}
                      date={d.date}
                      weight={d.weight}
                      reps={d.reps}
                      sets={d.sets}
                      note={d.note}
                      muscles={d.exercise.muscles.map(m => m.muscle)}
                    />;
                  })
                  : "No data"}
              </>
            )}
          </section>
        </div>
      </div>
    </>
  );
};

export default History;
