import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useSession } from "next-auth/react";
import { api } from "../../utils/api";

import { Navigation } from "../../components/Navigation";
import { RecordCard } from "../../components/RecordCard";

const History: NextPage = () => {
  const { data: sessionData } = useSession();
  const [skip, setSkip] = useState(0);
  const [perPage, setPerPage] = useState(5);
  const [date, setDate] = useState(new Date().toISOString().split("T")[0]);
  const { data } = api.workout.getUserWorkoutsByDate.useQuery({
    userId: sessionData?.user?.id || "",
    date: new Date(date).toISOString(),
    skip,
    perPage,
  });
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className="grid md:grid-cols-12">
        <div className="md:col-span-6 md:col-start-4">
          <section className="mb-2 p-2">
            <p className="text-sm text-gray-500">トレーニング履歴</p>
            <div className="mb-2">
              <label
                className="mb-2 block text-sm font-bold text-gray-700"
                htmlFor="date"
              >
                日付を選択
              </label>
              <input
                className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                id="date"
                type="date"
                placeholder="日付"
                value={date}
                onChange={(e) => setDate(e.target.value)}
              />
            </div>
            {data?.length && data?.length > 0
              ? data?.map((d) => {
                  return <RecordCard key={d.id} workout={d} />;
                })
              : "No data"}
          </section>
        </div>
      </div>
    </>
  );
};

export default History;
