import { useState, useCallback, useEffect } from "react";
import { useRouter } from "next/router";
import { type NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import { ChevronLeftIcon, ChevronRightIcon } from "@heroicons/react/20/solid";

import {
    Button,
    Heading,
    Navigation,
    ExerciseSelector,
    Loading,
    Timer,
} from "../../components";
import { api } from "../../utils/api";

type WorkoutProp = {
    date: string;
    selectedExerciseId: number;
    selectedExerciseName: string;
    weight: string;
    reps: string;
    sets: string;
    expiryTimeDelta: number;
};

const WorkoutRecorder: NextPage = () => {
    const router = useRouter();
    const [date, setDate] = useState<string>(
        new Date().toISOString().split("T")[0] || ""
    );
    const [error, setError] = useState<string>("");
    const [isEnd, setEnd] = useState<boolean>(false);

    const [selectedExerciseId, selectExerciseId] = useState(-1);
    const [selectedExerciseName, setExerciseName] = useState("");
    const [weight, setWeight] = useState<string>("50");
    const [reps, setReps] = useState<string>("10");
    const [sets, setSets] = useState<string>("-1");
    const [note, setNote] = useState<string>("");
    const [expiryTimeDelta, setExpiryTimeDelta] = useState<number>(120);

    const mutation = api.workout.add.useMutation();
    
    const send = async () => {
        await mutation
            .mutateAsync({
                date: new Date(date).toISOString(),
                weight: parseFloat(weight),
                reps: parseInt(reps),
                sets: parseInt(sets),
                note: note,
                exerciseId: selectedExerciseId,
            })
            .then(({ id }) => {
                window.sessionStorage.removeItem('workout');
                return Router.push(`/workout/${id}`);
            })
            .catch(() => {
                return;
            });
    };
    const handleExerciseClick = useCallback((exerciseId: number, exerciseName: string) => {
        selectExerciseId(exerciseId);
        setExerciseName(exerciseName);
    }, []);

    const startSets = () => {
        if (selectedExerciseId < 0) {
            setError("種目を選んでください");
            return;
        }

        saveSession("0");
        setSets("0");
        setError("");
    };

    const saveSession = (currentSet: string) => {
        const data: WorkoutProp = {
            date,
            selectedExerciseId,
            selectedExerciseName,
            weight,
            reps,
            sets: currentSet,
            expiryTimeDelta,
        };

        window.sessionStorage.setItem('workout', JSON.stringify(data));
    };
    const endSets = () => {
        const tmp = parseInt(sets) + 1;
        setSets(tmp.toString());
        setEnd(true);
    };

    const clear = async () => {
        window.sessionStorage.removeItem("workout");
        await router.push('/dashboard');
    };

    const onPrevSet = () => {
        const tmp = Math.max(parseInt(sets) - 1, 0);
        setSets(tmp.toString());
        saveSession(tmp.toString());
        setExpiryTimeDelta(expiryTimeDelta);
    };

    const onNextSet = () => {
        const tmp = parseInt(sets) + 1;
        setSets(tmp.toString());
        saveSession(tmp.toString());
        setExpiryTimeDelta(expiryTimeDelta);
    };


    useEffect(() => {
        const item = window.sessionStorage.getItem('workout');
        const workout = item && JSON.parse(item) as WorkoutProp;
        if(workout) {
            setDate(workout.date);
            selectExerciseId(workout.selectedExerciseId);
            setExerciseName(workout.selectedExerciseName);
            setWeight(workout.weight);
            setReps(workout.reps);
            setExpiryTimeDelta(workout.expiryTimeDelta);
            setSets(workout.sets);
        }
    }, []);

    return (
        <>
            <Head>
                <title>EveryWorkout</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Heading />
                <Navigation />
                <div className="grid md:grid-cols-12 bg-gray-50">
                    <div className="md:col-span-6 md:col-start-4 bg-white p-2">
                        {mutation.isLoading && <Loading />}
                        {mutation.isError && (
                            <p className="mb-2 rounded-lg bg-red-100 p-4 text-red-900">
                                エラーが発生しました: {mutation.error.data?.path}
                            </p>
                        )}
                        {error && (
                            <p className="mb-2 rounded-lg bg-red-100 p-4 text-red-900">
                                {error}
                            </p>
                        )}
                        {!isEnd && sets === "-1" && <>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="date"
                                >
                                    日付
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="date"
                                    type="date"
                                    placeholder="日付"
                                    value={date}
                                    onChange={(e) => setDate(e.target.value)}
                                />
                            </div>
                            <div className="mb-2">
                                <label className="block text-sm font-bold text-gray-700">
                                    種目
                                </label>
                                <ExerciseSelector
                                    selectedExerciseId={selectedExerciseId}
                                    handleExerciseClick={handleExerciseClick}
                                />
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="weight"
                                >
                                    重量
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="weight"
                                    type="number"
                                    step="2.5"
                                    placeholder="重量"
                                    value={weight}
                                    onChange={(e) => setWeight(e.target.value)}
                                />
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="reps"
                                >
                                    rep数
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="reps"
                                    type="number"
                                    placeholder="rep数"
                                    value={reps}
                                    onChange={(e) => setReps(e.target.value)}
                                />
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="username"
                                >
                                    インターバル(秒)
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="interval"
                                    type="number"
                                    placeholder="インターバル(秒)"
                                    value={expiryTimeDelta}
                                    onChange={(e) => setExpiryTimeDelta(parseInt(e.target.value) || 0)}
                                />
                            </div>
                            <Button onClick={startSets}>セットを始める</Button>
                        </>}
                        {!isEnd && sets !== "-1" && <>
                            <p className="text-xl font-bold">{selectedExerciseName}</p>
                            <div className="flex flex-col justify-center gap-2">
                                <div className="flex justify-center gap-2">
                                    <div><span className="text-3xl font-extrabold">{weight}</span>kg</div>
                                    <div><span className="text-3xl font-extrabold">{reps}</span>reps</div>
                                </div>
                                <div className="flex justify-center items-center">
                                    <ChevronLeftIcon onClick={onPrevSet} className="w-10 h-10 cursor-pointer"></ChevronLeftIcon>
                                    <span className="text-3xl font-extrabold">{parseInt(sets) + 1}</span>セット目
                                    <ChevronRightIcon onClick={onNextSet} className="w-10 h-10 cursor-pointer"></ChevronRightIcon>
                                </div>
                            </div>
                            <label
                                className="mb-2 block text-sm font-bold text-gray-700"
                            >
                                インターバル
                            </label>
                            <div className="shadow-lg rounded p-3 bg-gray-100">
                                <Timer expiryTimeDelta={expiryTimeDelta} onExpire={onNextSet}></Timer>
                            </div>
                            <div className="flex justify-center my-2">
                                <Button onClick={endSets}>セットを終了して記録</Button>
                                <Button onClick={() => void clear()}>記録しないで終了</Button>
                            </div>
                        </>}
                        {isEnd && <>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="date"
                                >
                                    日付
                                </label>
                                <p>{date}</p>
                            </div>
                            <div className="mb-2">
                                <label className="block text-sm font-bold text-gray-700">
                                    種目
                                </label>
                                <p>{selectedExerciseName}</p>
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="weight"
                                >
                                    重量
                                </label>
                                <p>{weight}kg</p>
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="reps"
                                >
                                    rep数
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="reps"
                                    type="number"
                                    placeholder="rep数"
                                    value={reps}
                                    onChange={(e) => setReps(e.target.value)}
                                />
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="sets"
                                >
                                    セット数
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="sets"
                                    type="number"
                                    placeholder="セット数"
                                    value={sets}
                                    onChange={(e) => setSets(e.target.value)}
                                />
                            </div>
                            <div className="mb-2">
                                <label
                                    className="mb-2 block text-sm font-bold text-gray-700"
                                    htmlFor="note"
                                >
                                    メモ
                                </label>
                                <input
                                    className="focus:shadow-outline w-full appearance-none rounded border py-2 px-3 leading-tight text-gray-700 shadow focus:outline-none"
                                    id="note"
                                    type="text"
                                    placeholder="メモ"
                                    value={note}
                                    onChange={(e) => setNote(e.target.value)}
                                />
                            </div>
                            {!mutation.isLoading && (
                                <Button onClick={() => void send()}>登録</Button>
                            )}
                        </>}
                    </div>
                </div>
            </main >
        </>
    );
};

export default WorkoutRecorder;
