import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { api } from "../utils/api";

import { Navigation } from "../components/Navigation";
import { RecordCard } from "../components/RecordCard";
import { MaximumCard } from "../components/MaximumCard";

const Dashboard: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data } = api.workout.getUserWorkouts.useQuery({
    userId: sessionData?.user?.id || "",
  });
  const { data: maximum } = api.maximum.getUserMaximums.useQuery({
    userId: sessionData?.user?.id || "",
  });
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <p>トレーニング記録</p>
      {data?.map((d) => {
        return <RecordCard key={d.id} workout={d} />;
      })}
      {maximum?.map((m) => {
        return <MaximumCard key={m.id} maximum={m} />;
      })}
    </>
  );
};

export default Dashboard;
