import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Navigation } from "../components/Navigation";
import { RecordCard } from "../components/RecordCard";

const records = [
  { id: 1, exercise: "ベンチプレス", weight: 62.5 },
  { id: 2, exercise: "スクワット", weight: 72.5 },
];
const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <p>ベスト</p>
      {records.map(({ id, exercise, weight }) => {
        return <RecordCard key={id} exercise={exercise} weight={weight} />;
      })}
    </>
  );
};

export default Dashboard;
