import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { api } from "../../utils/api";

import { Navigation } from "../../components/Navigation";
import { MaximumCard } from "../../components/MaximumCard";

const History: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const { exerciseId: ids } = router.query;
  const exerciseId = (Array.isArray(ids) ? ids[0] : ids) || "-1";

  const { data } = api.maximum.getUserMaximumsByExerciseId.useQuery({
    userId: sessionData?.user?.id || "",
    exerciseId: parseInt(exerciseId),
  });
  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className="grid md:grid-cols-12">
        <div className="md:col-span-6 md:col-start-4">
          <section className="mb-2 p-2">
            <p className="text-sm text-gray-500">ベスト更新履歴</p>

            {data?.length && data?.length > 0
              ? data?.map((d) => {
                  return (
                    <MaximumCard
                      key={d.id}
                      date={d.date}
                      exerciseName={d.exercise.name}
                      metrics_code={d.metrics_code}
                      value={d.value}
                    />
                  );
                })
              : "No data"}
          </section>
        </div>
      </div>
    </>
  );
};

export default History;
