import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { api } from "../../utils/api";
import { MinusCircleIcon, ViewColumnsIcon } from "@heroicons/react/20/solid";
import { useDarkMode } from "../../hooks/useDarkMode";

import {
  Bar,
  ResponsiveContainer,
  ComposedChart,
  XAxis,
  YAxis,
  Legend,
  Line,
  CartesianGrid,
  Tooltip
} from "recharts";
import { Heading, Navigation, MaximumCard, Loading, Button } from "../../components";

type ChartProp = {
  date: number;
  maximum?: number;
  volume?: number;
};

interface Iterable<ChartProp> {
  [Symbol.iterator]: Iterator<ChartProp>;
}

const History: NextPage = () => {
  const router = useRouter();
  const { exerciseId: ids } = router.query;
  const exerciseId = (Array.isArray(ids) ? ids[0] : ids) || "-1";
  const [isDeleteMode, setDeleteMode] = useState<boolean>(false);
  const { darkMode } = useDarkMode();

  const { data, isLoading, isSuccess } =
    api.maximum.getUserMaximumsByExerciseId.useQuery({
      exerciseId: parseInt(exerciseId),
    });

  const daily = api.workout.getUserWorkoutVolumeByExerciseId.useQuery({
    exerciseId: parseInt(exerciseId),
  });

  const test = data?.map<ChartProp>(x => {
    return {
      date: x.date.getTime(),
      maximum: x.value,
    }
  }) || [];

  const test2 = daily.data?.map<ChartProp>(x => {
    return {
      date: x.date.getTime(),
      volume: x.totalVolume
    }
  }) || [];
  const chartData = [
    ...test,
    ...test2,
  ];

  const lineData = data?.map(x => {
    return {
      date: x.date.getTime(),
      value: x.value
    }
  });

  const mutation = api.maximum.delete.useMutation();

  const toggleDeleteMode = () => {
    setDeleteMode(!isDeleteMode);
  };

  const deleteMaximum = async (id: string) => {
    await mutation.mutateAsync({
      id
    });
  };

  return (
    <>
      <Head>
        <title>EveryWorkout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <Navigation />
      <div className="grid md:grid-cols-12 dark:bg-gray-900">
        <div className="md:col-span-6 md:col-start-4">
          <section className="mb-2 p-2">
            {mutation.isLoading && <Loading />}
            {mutation.isSuccess && (
              <>
                <p className="rounded-lg bg-green-100 p-4 text-green-900">
                  削除完了
                </p>
              </>
            )}
            <p className="text-sm text-gray-700 dark:text-gray-300">種目別グラフ</p>
            {isLoading && <Loading />}
            {isSuccess && (<>
              <div className="w-full bg-white">
                <ResponsiveContainer
                  width="100%"
                  height={300}>
                  <ComposedChart
                    data={chartData}
                    margin={{ top: 5, right: 15, left: -5, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis
                      dataKey="date"
                      domain={['auto', 'auto']}
                      tickFormatter={(unixTime: Date) => new Date(unixTime).toLocaleDateString()}
                      type="number" />
                    <YAxis
                      yAxisId={1}
                      type="number"
                      dataKey="maximum"
                      domain={['dataMin - 5', 'dataMax + 5']} />
                    <YAxis
                      yAxisId={2}
                      orientation="right"
                      type="number"
                      dataKey="volume"
                      domain={[0, 'auto']} />
                    <Bar yAxisId={2} dataKey="volume" barSize={20} fill="#413ea0" />
                    <Line yAxisId={1} type="monotone" dataKey="maximum" />
                    <Legend align="center" verticalAlign="top"/>
                    <Tooltip
                      labelFormatter={(unixTime: Date) => new Date(unixTime).toLocaleDateString()} />
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
              <div className="mb-2 md:grid-span-3">
                <p className="text-sm text-gray-700 dark:text-gray-300 my-2">ベスト更新履歴</p>
                <Button onClick={toggleDeleteMode}>削除モード</Button>
              </div>
              <section className="grid md:grid-cols-3 gap-1">
                {data?.length && data?.length > 0
                  ? data?.map((d) => {
                    return (
                      <div key={d.id} className="md:grid-span-1 flex items-center">
                        {isDeleteMode ?
                          <MinusCircleIcon className="w-6 h-6 text-red-600 cursor-pointer" onClick={() => void deleteMaximum(d.id)}></MinusCircleIcon>
                          : ""}
                        <MaximumCard
                          date={d.date}
                          exerciseName={d.exercise.name}
                          metrics_code={d.metrics_code}
                          value={d.value}
                        />
                      </div>
                    );
                  })
                  : "No data"}
              </section></>
            )}
          </section>
        </div >
      </div >
    </>
  );
};

export default History;
